<!-- data-table js -->
<script src="{{ asset('/') }}adminity/files/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="{{ asset('/') }}adminity/files/bower_components/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
<script src="{{ asset('/') }}adminity/files/assets/pages/data-table/js/jszip.min.js"></script>
<script src="{{ asset('/') }}adminity/files/assets/pages/data-table/js/pdfmake.min.js"></script>
<script src="{{ asset('/') }}adminity/files/assets/pages/data-table/js/vfs_fonts.js"></script>
<script src="{{ asset('/') }}adminity/files/assets/pages/data-table/extensions/buttons/js/dataTables.buttons.min.js"></script>
<script src="{{ asset('/') }}adminity/files/assets/pages/data-table/extensions/buttons/js/buttons.flash.min.js"></script>
<script src="{{ asset('/') }}adminity/files/assets/pages/data-table/extensions/buttons/js/jszip.min.js"></script>
<script src="{{ asset('/') }}adminity/files/assets/pages/data-table/extensions/buttons/js/vfs_fonts.js"></script>
<script src="{{ asset('/') }}adminity/files/assets/pages/data-table/extensions/buttons/js/buttons.colVis.min.js"></script>
<script src="{{ asset('/') }}adminity/files/bower_components/datatables.net-buttons/js/buttons.print.min.js"></script>
<script src="{{ asset('/') }}adminity/files/bower_components/datatables.net-buttons/js/buttons.html5.min.js"></script>
<script src="{{ asset('/') }}adminity/files/assets/pages/data-table/js/dataTables.bootstrap4.min.js"></script>
<script src="{{ asset('/') }}adminity/files/bower_components/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
<script src="{{ asset('/') }}adminity/files/bower_components/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js"></script>
<!-- Custom js -->
<script src="{{ asset('/') }}adminity/files/assets/pages/data-table/extensions/buttons/js/extension-btns-custom.js"></script>
